apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-weather-api-qa
  namespace: argocd
spec:
  project: myapp-qa
  source:
    repoURL: 'https://github.com/Liset-Cabrera/my-gitops.git'
    targetRevision: release/*
    path: 'charts/myapp/weather-api'
    helm:
      valueFiles:
        - values.yaml
        - overlays/qa-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true