apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/Liset-Cabrera/my-gitops.git
  destinations:
    - namespace: myapp-dev
      server: https://kubernetes.default.svc
