apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.config }}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.configmapName" . }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources| nindent 12 }}
          {{- end }}