apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "myapp.fullname" . }}
  port:
    targetPort: http 
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | default ""}}
  {{- end }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
  {{- end }}