replicaCount: 2

image:
  tag: "2.0"

service:
  port: 8090

route:
  host: quarkus-app.apps-crc.testing
  tls:
    enabled: true
    termination: edge

resources:
  requests:
    cpu: "25m"
    memory: "128Mi"
  limits:
    cpu: "25m"
    memory: "128Mi"

config:
  LOG_LEVEL: warn